const modeNotificationText = {
    observer: 'Ward Mode: Observer',
    sentry: 'Ward Mode: Sentry',
    navigate: 'Navigation Mode',
    brush: 'Draw Mode: Brush',
    icon: 'Draw Mode: Icon',
    point: 'Draw Mode: Point',
    linestring: 'Draw Mode: Line',
    polygon: 'Draw Mode: Polygon',
    shape: 'Draw Mode: Shape',
    modify: 'Draw Mode: Modify',
    rotate: 'Draw Mode: Rotate',
    scale: 'Draw Mode: Scale',
    skew: 'Draw Mode: Skew',
    drag: 'Draw Mode: Drag',
    delete: 'Draw Mode: Delete',
    line: 'Measure Mode: Line',
    circle: 'Measure Mode: Circle',
    treeEnable: '<span>Navigation Mode</span><span>Trees: On</span>',
    treeDisable: '<span>Navigation Mode</span><span>Trees: Off</span>',
    nightOn: 'Nighttime Vision',
    nightOff: 'Daytime Vision',
    darknessOn: 'Darkness: On',
    darknessOff: 'Darkness: Off',
    saveSuccess: 'Map saved.',
    saveFailed: 'Map save failed.',
    share: 'Map url copied to clipboard.',
};

export default modeNotificationText;
